# 47장 에러 처리

### 47.1 에러 처리의 필요성

에러가 발생하지 않는 코드를 작성하는 것은 불가능하다. 에러는 언제나 발생할 수 있다. 발생한 에러를 방치하면 프로그램은 강제 종료된다.

try ... catch 문을 사용해 발생한 에러에 적절히 대응하면 강제 종료 없이 계속해서 코드를 진행시킬 수 있다.

직접 에러를 발생하지 않는 예외적인 상황이 발생할 수 있다. 예외적인 상황에 적절히 대응해야 에러로 이어질 가능성을 줄일 수 있다.

이처럼 에러나 예외적인 상황에 대응하지 않으면 프로그램은 안정성을 잃고 강제 종료될 것이다. 에러나 예외적인 상황은 너무나 다양하기에 조치없이 강제 종료 된다면 원인을 파악하여 대응하기 어렵다. 따라서 코드를 작성할때 언제나 에러와 예외적인 상황이 발생할 수 있음을 인식하고, 이에 대응하는 코드를 작성하는 것이 중요하다.



### 47.2 try ... catch ... finally 문

기본적으로 에러 처리를 구현하는 방법은 2가지 있다.

1. 예외적인 상황이 발생하면 반환하는 값을 if문, 단축 평가, 옵셔널 체이닝 연산자를 통해 확인해 처리하는 방법
2. 에러 처리 코드를 미리 등록하고 에러가 발생하면 에러 처리 코드로 점프하도록 하는 방법

try ... catch ... finally 문은 두 번째 방법이다. 일반적으로 이 방법을 에러 처리라 한다. try ... catch ... finally는 이름대로 3개의 코드 블록으로 구성된다. 실행하면 try 코드 블록이 실행되는데 try 코드 블록에 포함된 문에서 에러가 발생하면 발생한 에러는 catch 문의 err 변수에 전달되고 catch 코드 블록이 실행된다. finally 블록은 에러 발생과 상관없이 반드시 한 번 실행된다. try ... catch ... finally 문으로 에러를 처리하면 프로그램이 강제 종료되지 않는다.



### 47.3 Error 객체

Error 생성자 함수는 에러 객체를 생성한다. Error 생성자 함수에는 에러를 상세히 설명하는 에러 메시지를 인수로 전달할 수 있다.

Error 생성자 함수가 생성한 에러 객체는 message 프로퍼티와 stack 프로퍼티를 갖는다. message 프로퍼티의 값은 Error 생성자 함수에 인수로 전달한 에러 메시지이고, stack 프로퍼티의 값은 에러를 발생시킨 콜 스택의 호출 정보를 나타내는 문자열이며 디버깅 목적으로 사용한다.

JS는 생성자 함수를 포함해 7가지 에러 객체를 생성할 수 있는 Error 생성자 함수를 제공한다. SyntaxError, ReferenceError, RangeError, URIError, EvalError 생성자 함수가 생성한 에러 객체의 프로토타입은 모두 Error.prototype을 상속받는다.

<table><thead><tr><th width="167" align="center">생성자 함수</th><th align="center">인스턴스</th></tr></thead><tbody><tr><td align="center">Error</td><td align="center">일반적 에러 객체</td></tr><tr><td align="center">SyntaxError</td><td align="center">자바스크립트 문법에 맞지 않는 문을 해석할 때 발생하는 에러 객체</td></tr><tr><td align="center">ReferenceError</td><td align="center">참조할 수 없는 식별자를 참조했을 때 발생하는 에러 객체</td></tr><tr><td align="center">TypeError</td><td align="center">피연산자 또는 인수의 데이터 타입이 유효하지 않을 때 발생하는 에러 객체</td></tr><tr><td align="center">RangeError</td><td align="center">숫자값의 허용 범위를 벗어났을 때 발생하는 에러 객체</td></tr><tr><td align="center">URIError</td><td align="center">encodeURI 또는 decodeURI 함수에 부적절한 인수를 전달할 때 발생하는 에러 객체</td></tr><tr><td align="center">EvalError</td><td align="center">eval 함수에서 발생하는 에러 객체</td></tr></tbody></table>



### 47.4 throw 문

Error 생성자 함수로 에러 객체를 생성한다고 에러가 발생하는 것은 아니다. 즉, 에러 객체 생성과 에러 발생은 의미가 다르다. 에러를 발생시키려면 try 코드 블록에서 throw 문으로 에러 객체를 던져야 한다.

throw 문의 표현식은 어떤 값이라도 상관없지만 일반적으로 에러 객체를 지정한다. 에러를 던지면 catch 문의 에러 변수가 생성되고 던져진 에러 객체가 할당된다. 그리고 catch 코드 블록이 실행되기 시작한다.

```javascript
try{
    throw new Error('something Wrong !')
}catch(error){
    console.log(error)
}
```



### 47.5 에러의 전파

에러는 호출자 방향으로 전파된다. 적절한 시점에 throw된 에러를 캐치하지 않으면 호출자 방향으로 에러가 전파되고, 프로그램이 강제 종료될 수 있다. 따라서 throw된 에러를 캐치하여 적절히 대응할 수 있도록 코드를 작성해야 한다.
